### ISSUE TITLE
derelict/util/loader.d cannot be read

### ISSUE THREAD

**Issue by volomike** [p0nce/DerelictCocoa#7]
I tried running the example, but got an error.

$ dmd window.d
derelict/cocoa/runtime.d(43): Error: module loader is in file 'derelict/util/loader.d' which cannot be read
import path[0] = /Library/D/dmd/src/phobos
import path[1] = /Library/D/dmd/src/druntime/import

**Comment by extrawurst** [comment]
the derelict packages use the `dub` format and are supposed to be build using the dub tool and not a raw d compiler. please visit this page for more infos: http://code.dlang.org/getting_started

normally it is enough to have dub installed and go into the projects directory containing the `dub.json`or `package.json` and simply run `dub`

**Comment by p0nce** [comment]
Thanks @Extrawurst.
@volomike : you will like DUB :)
